# Generated by Django 4.0.6 on 2022-08-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggroup',
            name='has_value',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
