# Generated by Django 4.0.6 on 2022-08-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_management_system', '0003_bom_item_material_project_delete_tag_delete_taggroup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='lib_ref',
        ),
    ]
