# Generated by Django 4.0.6 on 2022-08-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management_system', '0004_rename_name_item_lib_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expected_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='free_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unavailable_count',
            field=models.IntegerField(null=True),
        ),
    ]
