# Generated by Django 4.0.6 on 2022-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management_system', '0006_remove_item_free_count_remove_item_unavailable_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='feature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
