# Generated by Django 4.0.6 on 2022-08-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_management_system', '0009_remove_material_item_name_item_free_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='price',
            new_name='unit_price',
        ),
    ]
