# Generated by Django 4.0.6 on 2022-08-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management_system', '0010_rename_price_material_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='is_group',
        ),
        migrations.AddField(
            model_name='item',
            name='is_group',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=5),
        ),
    ]
