# Generated by Django 4.0.6 on 2022-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management_system', '0012_material_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='status',
        ),
        migrations.AddField(
            model_name='material',
            name='is_free',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=5),
        ),
    ]
