# Generated by Django 4.0.6 on 2022-08-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management_system', '0015_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
