# Generated by Django 4.0.6 on 2022-08-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management_system', '0018_item_footprint_item_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='footprint',
        ),
        migrations.RemoveField(
            model_name='item',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='item',
            name='ds_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lib_ref',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='part_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
