# Generated by Django 4.0.6 on 2022-09-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management_system', '0019_remove_item_footprint_remove_item_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='material',
        ),
        migrations.AddField(
            model_name='bom',
            name='material_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
